.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..

.TH i3status 1 "MAY 2009" Linux "User Manuals"

.SH NAME
i3status \- Generates a status line for wmii
.SH SYNOPSIS
.B i3status
.RB [\|\-c
.IR configfile \|]

.SH DESCRIPTION

.B i3status
is a small program (around 500 SLOC) for filling wmii's status bar via its 9P
pseudo filesystem. It is designed to be very efficient by issuing a very
small number of systemcalls (as the bar should be updated every second or at
your specified interval). This ensures that even under high load, your status bar
is updated correctly and it saves a little bit of battery life by not spawning
new processes every second like shell scripts do.

.SH CONFIGURATION
.TP
.B wlan
Specifies the name of your WLAN interface (e.g. wlan0 or ath0 or eth1). Don't
specify if you don't have a WLAN interface or if it should not be displayed.

.TP
.B eth
Specifies the name of your ethernet interface (e.g. eth0). Don't specify if you
don't have an ethernet interface or if it should not be displayed.

.TP
.B wmii_path
Specifies the path to the rbar-folder of your mounted wmii pseudo file system
(e.g. /mnt/wmii/rbar/). It has to be terminated by a slash.

.TP
.B time_format
Format for the time/date to be displayed. See strftime(3) or date(1). Don't
specify it if you don't want the time to be shown.

.TP
.B battery
The number of the battery you want to display. This option can be specified
multiple times to display multiple batteries. Don't specify it if you don't
have a battery. To get the number of the specific battery, see
/sys/class/power_supply/BAT*

If you want i3status to use the last full capacity instead of the design capacity
of the battery, specify the f-flag, like this:

.Vb 10
# Use the last full capacity
battery 0,f
.Ve

.TP
.B run_watch
You can specify this directive multiple times. Each line first has a name (one
word, separated by space) followed by a path (can contain wildcards, given to
glob(3)). The path is the path to a PID-file which contains just the process ID
of a process. i3status will then check if the process is still running and
displays "yes" or "no" depending on the status. This is useful for displaying
if your VPN is running, or dhclient for DHCP and so on...

.TP
.B order
Followed by a comma separated list of the modules (run, wlan, eth, battery,
load, time) this directive specifies the order of the information which should
be displayed. An order is accomplished by prefixing the files in wmii's /rbar
directory with a number, that is 0VPN, 1DHCP, 2time and so on..

.TP
.B color
If specified, color mode is on. This affects WLAN which will be displayed red
if WLAN is down and the run_watch system which will display the status in
red/green.

.TP
.B get_ethspeed
Get current speed of the ethernet interface using the same mechanism as
ethtool. You need to start i3status with root privileges to use this.

.TP
.B get_cpu_temperature
Gets the temperature of the first thermal zone or the specified thermal zone
(if any). Use it to display your CPU temperature.

.TP
.B normcolors
Specifies the colors for background/border in the same format (html colorcodes)
as wmii's configuration (just the last two values), that is #222222 #333333 for
example. Text color will be determined automatically (red/green/#888888),
depending on context.

.TP
.B interval
Specifies the interval in which the status bar will be updated. If you got a
very slow system or feel you don't need so much information, you may want to
increase it.

.SH FILES
.TP
.B /etc/i3status.conf
System-wide configuration file.

.SH EXAMPLE CONFIGURATION
.PP
.Vb 10
\&wlan wlan0
\&eth eth0
\&wmii_path /mnt/wmii/rbar/
\&time_format %d.%m.%Y %H:%M:%S
\&battery 0
\&battery 1,f
\&run_watch DHCP /var/run/dhclient*.pid
\&run_watch VPN /var/run/vpnc*.pid
\&order run,wlan,eth,battery,load,time
\&normcolors #000000 #333333
\&color
\&get_cpu_temperature
.Ve

.SH MOUNTING WMII'S PSEUDO FILESYSTEM
As of now (February 2009, Linux 2.6.28) you can mount wmii's 9P pseudo filesystem using:
.PP
.Vb 3
mount -t 9p -o rw,trans=unix,uname=michael,dfltuid=1000,dfltgid=50,name=michael,noauto,noextend /tmp/ns.michael.:0/wmii /mnt/wmii 
# Perhaps you need to load module 9pnet_fd if that does not work
modprobe 9pnet_fd
.Ve

.SH BUGS
Sometimes, i3status crashes when the wlan interface vanishes (killswitch). I
haven't yet found the bug, as it is not reproducible. If you can reproduce
this, please fix it and send me a patch.

.SH SEE ALSO
.BR strftime (3),
.BR date (1),
.BR glob (3)

.SH AUTHORS
Michael Stapelberg <michael+i3status at stapelberg dot de>

Thorsten Toepper <atsutane at freethoughts dot de>

.SH WEBSITE
See http://i3.zekjur.net/i3status for the newest release.
