#!/bin/sh

set -e

# Allow users to get the speed of ethernet interfaces. This is not a security
# issue as i3status only queries the speed, it does not change any
# configuration.
if [ -x /sbin/setcap ]
then
	setcap cap_net_admin=ep /usr/bin/i3status || true
else
	echo "setcap(8) not installed. You need to set CAP_NET_ADMIN \
to be able to query the network link bandwidth without root privileges."
fi

#DEBHELPER#

exit 0
